# Generated by Django 4.0.5 on 2022-07-04 09:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlucoseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(default=uuid.uuid4)),
                ('seriennummer', models.CharField(max_length=255)),
                ('gerätezeitstempel', models.DateTimeField()),
                ('aufzeichnungstyp', models.IntegerField()),
                ('glukosewert_verlauf', models.IntegerField(help_text='mg/dL')),
                ('glukose_scan', models.IntegerField(help_text='mg/dL')),
            ],
        ),
    ]
